### ISSUE TITLE
how  to configure the 4*4 MIMO

### ISSUE THREAD

**Issue by ozawali** [IMDEANetworksWNG/UbiLocate#1]
Thanks for your great works. since your paper use the AoD, so I want to know how to configure the 4*4 MIMO and obtain the CSI. Thanks.

**Comment by alejandroBlancoPizarro** [comment]
Hi azawali,

Thanks for your interest in UbiLocate. We are working on the GitHub project.

We have just enabled the CSI extraction of 4x4 MIMO. Please, clone the new status of the project and follow the new instructions.

Best,
Alejandro

**Comment by ozawali** [comment]
Thanks! it works well. Great work.
