### ISSUE TITLE
How to tune the shell script for duplicate the mimo 4x4 ToF measurement?

### ISSUE THREAD

**Issue by quantumhub** [IMDEANetworksWNG/UbiLocate#10]
Is the 4x4 ToF result in paper obtained from 1x1 and 4x4 mixed CSIs sequence, or pure 4x4 sequence?
How to tune the shell script for that? Thanks!

**Comment by alejandroBlancoPizarro** [comment]
We obtained our results using 1x1.We are not sure how tof will perform using 4x4.

Best,
Alejandro
