### ISSUE TITLE
Why use fft for time analysis? 

### ISSUE THREAD

**Issue by crownz-sec** [IMDEANetworksWNG/UbiLocate#16]
In code UbiLocate/matlab_scripts/Extract_Path_Parameters/Decompose_2D.m, from line 33 to line 37 code is
``` matlab
%% MP loop
for ii_path = 1:N_paths
    %% Time analysis
    csi_data_t = fft(csi_data_0, 4*1024, 1);
    Time_spectrum = sum(abs(csi_data_t(:, :)).^2, 2);
```
Why use fft for time analysis? My understanding is that CSI is frequency domain information. If you want the corresponding time domain information, you should do ifft. 
And you have the following statement in your paper:
![image](https://user-images.githubusercontent.com/47936479/139061753-8d6339fe-0661-4cb7-8d46-ce3ef75cfcf0.png)
I can't understand the correspondence between the code and the paper.

**Comment by crownz-sec** [comment]
I see, but if there are no advantages, why do it?

**Comment by alejandroBlancoPizarro** [comment]
Hi,

Since both can do the job, we just chose fft.

In any case, thanks for realizing about this misunderstand between the code and the paper. We appreciate your feedback. We will update the code to perform an ifft instead of an fft.

Best,
Alejandro

**Comment by crownz-sec** [comment]
ok, very thanks for your reply!
