### ISSUE TITLE
With 802.11n setting, how many antennas did you use for the experiment?

### ISSUE THREAD

**Issue by crownz-sec** [IMDEANetworksWNG/UbiLocate#17]
In your experimental implementation, how many antennas did you use when you measure the AOA accuracy of SpotFi in 802.11n and 802.11ac settings? Is it three or four? And how many antennas for UbiLocate in 802.11n settings?

**Comment by alejandroBlancoPizarro** [comment]
Hi,

It is written in the paper. But, for 802.11n the number of antennas is 3 and bw is 40MHz while for 802.11ac 4 antennas and 80MHz.

Best,
Alejandro

**Comment by crownz-sec** [comment]
okay, thanks

**Comment by crownz-sec** [comment]
I still have an implementation-related question, how many subcarriers do you use when you implement SpotFi on an 802.11AC device? Did you change the spotfi code to handle 256 subcarriers?

**Comment by alejandroBlancoPizarro** [comment]
Hi,

We modify the code to handle 256 subcarriers.

Best,
Alejandro

**Comment by crownz-sec** [comment]
> Hi,
> 
> We modify the code to handle 256 subcarriers.
> 
> Best, Alejandro

Okay, And when you implement UbiLocate on your 802.11ac devices with 802.11n setting, do you use 30 subcarriers or 256 subcarriers?

**Comment by alejandroBlancoPizarro** [comment]
802.11n has 128 subcarriers and the ASUS router is able to get all of them. We also modified it to support 128 subcarriers

**Comment by crownz-sec** [comment]
> 802.11n has 128 subcarriers and the ASUS router is able to get all of them. We also modified it to support 128 subcarriers

okay, I know, very thanks.
