### ISSUE TITLE
A question about IP setting

### ISSUE THREAD

**Issue by crownz-sec** [IMDEANetworksWNG/UbiLocate#19]
In the documentation, it says that the IP range should be 192.168.2.X. However, I found that this setting caused some minor problems on my existing network, I was wondering if it could be set to 192.168.1.X?

**Comment by alejandroBlancoPizarro** [comment]
Hi,

You can use the IP in the range of 192.168.1.X  but you have to change the IP addresses on the files

**Comment by crownz-sec** [comment]
okay, thanks
