### ISSUE TITLE
Can I set the channel frequency, channel bandwidth, and packet rate?

### ISSUE THREAD

**Issue by U201213632** [IMDEANetworksWNG/UbiLocate#2]
Thanks for your great work.
I want to use your CSI tool for research purposes.
Before, I want to know can I set the channel frequency, channel bandwidth, and packet rate?
Thanks.

**Comment by ozawali** [comment]
The command is :
echo "Setting up the transmitter"
sshpass -p ${ps} ssh ${us}@192.168.2.${tx} /jffs/LEGACY160/./configcsi.sh 157 80   # 157 is the channel index and 80 is the BW

But, the packet rate is unknown.

BR

**Comment by alejandroBlancoPizarro** [comment]
Hi,

Yes, you can set the channel frequency and channel BW. I am going to update the GitHub project so that you can tune those parameters.

Best,
Alejandro

**Comment by alejandroBlancoPizarro** [comment]
Concerning the packet rate. At the moment, it sends a packet every 20ms

**Comment by ozawali** [comment]
Thanks. This is a great work. @alejandroBlancoPizarro

**Comment by U201213632** [comment]
Thanks!!!!  @ozawali @alejandroBlancoPizarro
