### ISSUE TITLE
A question about ToF estimation.

### ISSUE THREAD

**Issue by crownz-sec** [IMDEANetworksWNG/UbiLocate#20]
Because I want to test the accuracy of ToF first, I started the ToF extraction before the antenna array was configured. But the .pcap filesI got was different from the .pcap files you provided, and the subsequent ToF extraction would also be wrong.
Can ToF estimates be used without a configured antenna array? Is it feasible to estimate ToF without CSI?

**Comment by alejandroBlancoPizarro** [comment]
Hi,

You need to configure the antenna and use CSI to remove time uncertainty that the ToF might contain.

**Comment by crownz-sec** [comment]
I see the problem with ToF estimation. But if I want to process the timestamp myself, how can I only get the timestamp information without CSI?

**Comment by crownz-sec** [comment]
And what is the time unit of the output of Compute_ToF_music.m?

**Comment by alejandroBlancoPizarro** [comment]
The output is in meters

**Comment by crownz-sec** [comment]
> The output is in meters

Okay. Thanks for reply.
