### ISSUE TITLE
Router networks cannot be searched when some bash files are executed.

### ISSUE THREAD

**Issue by crownz-sec** [IMDEANetworksWNG/UbiLocate#21]
I executed some bash files of ToF extract, but after that, I found that I couldn't find the WiFi network. And when I rebooted the router, I was able to search the network again. Is that normal?

**Comment by alejandroBlancoPizarro** [comment]
Hi,

Not sure about the WiFi, I always connected the router by Ethernet.

**Comment by crownz-sec** [comment]
Okay,thanks.
