### ISSUE TITLE
What is the content of the reference80true.mat file in /matlab_scripts/Extract_ToF?

### ISSUE THREAD

**Issue by crownz-sec** [IMDEANetworksWNG/UbiLocate#23]
The variable in `reference80true.mat` is named reference and is loaded by `compute_tof_music.m`. After that, you did the hadamard division to calibrate the CSI, so when you calibrate the ToF, you still need to calibrate the CSI, right?

And which pair of antennas does the reference belongs to? I can't find any information about the antennas pair you used for ToF estimation.

**Comment by alejandroBlancoPizarro** [comment]
Hi,

You are right, we did not explain it on the paper. The idea is quite similar as the calibration in the UbiLocate paper Section 3.1 Extracting CSI. We aim to remove the echos that the CSI data contains, to do so we apply a deconvolution and that is why we use a hadamard division in the MATLAB code.

The CSI data where captured by a pair of ASUS routers connecting the first chains of both (the rightmost chains on the ASUS).

**Comment by crownz-sec** [comment]
Okay, and is the rightmost chains correspond to antenna 1's chain in your device image?

**Comment by alejandroBlancoPizarro** [comment]
Yes it does

**Comment by crownz-sec** [comment]
okay, thanks.
