### ISSUE TITLE
The resulting ToF pcap file is different from the given test file.

### ISSUE THREAD

**Issue by crownz-sec** [IMDEANetworksWNG/UbiLocate#24]
The given test pcap file in `/ToF/traces/test` is shown below:
![image](https://user-images.githubusercontent.com/47936479/146529298-b52e61e6-2769-494f-b13c-75f15caba274.png)
But what I got is something like this:
![image](https://user-images.githubusercontent.com/47936479/146528981-012dcf95-022c-4a3e-af94-3bc3326d0cb7.png)

They looks quite different and the frame interval is not 4ms. Since I can extract ToF, all the files I got are like this. Is it right? And if it's wrong, what's the problem?

**Comment by alejandroBlancoPizarro** [comment]
I think it is ok. Which was the ToF value? If the ToF value is ok, it means that the pcap is fine.

Try by cables first.

Best,
Alejandro

**Comment by crownz-sec** [comment]
> I think it is ok. Which was the ToF value? If the ToF value is ok, it means that the pcap is fine.
> 
> Try by cables first.
> 
> Best, Alejandro

Thanks, I will try it.
