### ISSUE TITLE
How to obtain the reference CSI for the calibration of ToF?

### ISSUE THREAD

**Issue by crownz-sec** [IMDEANetworksWNG/UbiLocate#26]
When I do it myself, I always have a reboot problem, so I don't know if I'm doing it right. Therefore, I would like to ask the author how to obtain reference CSI and ToF measurements. Can you describe exactly what you did when extracting ToF measurements?

**Comment by alejandroBlancoPizarro** [comment]
Hi,

Not sure why you need a CSI reference for ToF, the CSI reference is already on the MATLAB code that we provided on GitHub.

For the rebooting problem, I explained you on the other issue that this happens everytime time that you execute two times reload.sh.

Hope this can help.

Best,
Alejandro

**Comment by crownz-sec** [comment]
Thanks to what you said, I see. I was wrong before. CSI of multiple antennas needs to be calibrated because random phase differences between multiple antennas need to be eliminated. However, the ToF measurement requires only one antenna on the device, so there is no need to eliminate the phase difference between antennas. 
But I still have I question. In the Extracting ToF section of README.md, you said:

> This part is configured to send SISO packets, but it send 4x4 MIMO every 32 packets so that computing AoA and AoD at the same time as ToF is also possible.

If you have no reference CSI, the random phase offset between antennas can't be removed. And then, you can't get accurate and reliable estimates of AoA and AoD. Moreover, since extracting CSI first and then extracting ToF extraction will cause reboot. From this point of view, I can't imagine what this operation would do.

**Comment by alejandroBlancoPizarro** [comment]
Hi,

I think I answered you on the previous issue. In any case, you can extract CSI while getting the ToF.

You firstly need to extract a reference CSI executing the ToF, the 4x4 MIMO of every 32 packets. Afterward, you can extract tof and CSI at the same time.

Best,
Alejandro

**Comment by crownz-sec** [comment]
Okay, thanks!
