### ISSUE TITLE
Is there a linear phase offset of CSI between the received packets?

### ISSUE THREAD

**Issue by crownz-sec** [IMDEANetworksWNG/UbiLocate#28]
I want to do know is there a linear phase offset of CSI between the received packets should be calibrated like SpotFi? I have tested some CSI data, it seems that there does not exists such an offset. But I am not sure, so I want to ask to confirm the situation.

**Comment by alejandroBlancoPizarro** [comment]
Hi,

The CSI measurements between packets have a linear phase offset across subcarriers due to the delay introduced by the packet detector. 

This is common for every off-the-shelf WiFi device.

Best,
Alejandro

**Comment by crownz-sec** [comment]
Okay, thanks for reply!
