### ISSUE TITLE
How to calibrate AoD and AoA

### ISSUE THREAD

**Issue by HuangZengt** [IMDEANetworksWNG/UbiLocate#4]
Hi, Thank you for your help before.

And now I have a new problem ,there is no packages can be received when using the method you given to calibrate the router .

Otherwise,  I'll appreciate it if you provide the matlab_scripts to extract ToF.

Best regards,

Hz

**Comment by alejandroBlancoPizarro** [comment]
Hi Hz,

Sorry, I do not understand your problem about not packages received when using the method to calibrate. Could you please explain another time?

Concerning ToF, the code for extracting the ToF can be found at https://github.com/IMDEANetworksWNG/UbiLocate#extracting-tof

Best,
Alejandro

**Comment by alejandroBlancoPizarro** [comment]
Hi Hz,

Sorry, I've just realized that I did not uploaded the MATLAB files for ToF, please update the project.

Best,
Alejandro

**Comment by HuangZengt** [comment]
Thank you for your help.
