### ISSUE TITLE
How to configure packet rate

### ISSUE THREAD

**Issue by HuangZengt** [IMDEANetworksWNG/UbiLocate#5]
Thanks for your great work.

Now I want to know how to configure packet rate and what should I do to increase the rate of sending packets. 

I will appreciate for your help.

Best regards,
Hjdkl

**Comment by alejandroBlancoPizarro** [comment]
Dear Hjdkl,

At the moment the data rate cannot be tunable. The platform sends packets every 20ms if you are using Extracting CSI. How much data rate would you need?

Best,
Alejandro

**Comment by HuangZengt** [comment]
Dear Alejandro，

I want to send at least 200 packets per second.

**Comment by sophiajs1** [comment]
Hello,   i am experiencing the same issue. I actually was able to extract CSI by the CSI tool of UbiLocate. Based on the work of UbiLocate, however, i want to set a high packet rate (>500 packets per second) to study human behavior recognition.  How to set packet rate?

I will appreciate for your help.

Best,
sophia



I actually was able to hack Nexmon into the Kali build scripts.
Thanks for your great work.
I want to use your CSI tool for research purposes.
Before, I want to know can I set the channel frequency, channel bandwidth, and packet rate?
Thanks.

**Comment by sophiajs1** [comment]
Hello, i am experiencing the same issue. I actually was able to extract CSI by the CSI tool of UbiLocate. Based on the work of UbiLocate, however, i want to set a high packet rate (>500 packets per second) to study human behavior recognition. How to set packet rate?

I will appreciate for your help.

Best,
sophia

**Comment by ozawali** [comment]
@alejandroBlancoPizarro  Hi, I also want to know how to change the rate of collecting csi. I want at least 500 packets per second. Thanks.

**Comment by alejandroBlancoPizarro** [comment]
Hi all,

We are going to upload a new sender version where you can tune the packet rate. From our test, the maximum packet rate is 2ms, we hope that is fine from your side.

Please, stay tuned. I will write a comment here once the new sender version is available so that you can update the project.

Best,
Alejandro

**Comment by alejandroBlancoPizarro** [comment]
Hi all,

I am on vacation now. I will do it once I come back to work (beginning of September).

You may use the sender version in tofsoftware that sends packet every 4ms. If you want to extract the CSI for four chain, change in config.sh the line: CONFIG=$(./makecsiparams -e 1 -m ff:ff:00:12:34:56 -c 0xe29b -C 0x1 -N 0x1 -b 0x88) to this one: CONFIG=$(./makecsiparams -e 1 -m ff:ff:00:12:34:56 -c 0xe29b -C 0xf -N 0x1 -b 0x88).

Best,
Alejandro

**Comment by HuangZengt** [comment]
Thanks for your help!

**Comment by alejandroBlancoPizarro** [comment]
Hi all,

The faster version is available, this one allow you to tune the packet rate. 

Take a look at it here: https://github.com/IMDEANetworksWNG/UbiLocate#extracting-csi-faster

Let me know if it is working as the old version

Best,
Alejandro

**Comment by HuangZengt** [comment]
Hi  Alejandro,

I found that the number of packets received in the new version is much less than the number of packets sent.

Wish your help. 

Best,
Hjdkl

**Comment by HuangZengt** [comment]
there is my test.
![image](https://user-images.githubusercontent.com/64193566/133015695-9fb23e22-b7cd-4c4b-8544-c3c79f1a290c.png)
![image](https://user-images.githubusercontent.com/64193566/133015716-0fceffa4-468b-42ed-a0f1-c5c997d093be.png)

When I send 100 packets, the number of packets received should be 100x4x4=1600 , but tcpdump is only received   240 packets.

Wish your help. @alejandroBlancoPizarro

**Comment by alejandroBlancoPizarro** [comment]
Hi  Hjdkl,

Which is the periodicity?

Best,
Alejandro

**Comment by HuangZengt** [comment]
Hi Alejandro,

I use defaults setting to run the program in faster version, it is 0xe000 and means 8ms.

Best,
Hjdkl

**Comment by alejandroBlancoPizarro** [comment]
Hi Hjdkl,

Do you files have executable permissions? Please, copy the output of ls -l of the files inside the router

Best,
Alejandro

**Comment by HuangZengt** [comment]
Hi Alejandro,

The output is as follows:
![image](https://user-images.githubusercontent.com/64193566/133081047-ce5c3ff0-efab-4112-b01f-64647e880871.png)

**Comment by alejandroBlancoPizarro** [comment]
Sorry, I did not explain my self clearly. Show the output of ls -l of the folder raw_perf. If you do not have it, please do a pull to update the project.

Best,
Alejandro

**Comment by HuangZengt** [comment]
I put the files of rawperf into send_periodically folder, as follows:


![image](https://user-images.githubusercontent.com/64193566/133090691-f2200227-513a-4d7f-92b4-15027469ba67.png)

**Comment by alejandroBlancoPizarro** [comment]
OK, the permissions are ok. Could you please run it but with 1x4 setting?

**Comment by HuangZengt** [comment]
The problem is same as 4x4 setting when I set 1x4.

![image](https://user-images.githubusercontent.com/64193566/133253275-7a3d9081-c463-4eb7-a678-434a1a48d1f0.png)

**Comment by alejandroBlancoPizarro** [comment]
Not sure why. Did you change the firmware of the router? Maybe this is the problem.

Best,
Alejandro

**Comment by HuangZengt** [comment]
Hi Alejandro,

I  try the faster version again, but the number of packets received is still much less than the packets setting. In addition, I have some problems about configurations in Rx and Tx. 

1. In _config_rx. sh and config. sh_,  why are they 4ms and 8ms respectively rather than both  8ms? 
  
![image](https://user-images.githubusercontent.com/64193566/135099341-53945d95-e420-4d8a-95f2-542e1237204c.png)

Further, I change them to 8ms and there are errors---'__nex_driver_io: error'
![image](https://user-images.githubusercontent.com/64193566/135103631-727a4097-6707-4972-836a-3fd307eb39f9.png)

2.  I have run the pcap files provided in ...\traces\test_1ss_rawperf\trace4.pcap, 
![image](https://user-images.githubusercontent.com/64193566/135105387-8a66428f-926b-4474-860f-790bc9ff1b54.png)
 does the tao_packets represent timestamp? and the sampling rate is about 120 Hz. I have run the pcap files provided in ...\traces\test_4ss_rawperf\trace4.pcap, but the csi_data are all zero.
![image](https://user-images.githubusercontent.com/64193566/135106107-7f158553-97ae-4a0d-8358-092e62aa9dff.png)

3.  I have changed firmware of the router into the latest version and still meet the above problem.

In all, the number of received packets are much less than the predefined number. 

Wish your help. @alejandroBlancoPizarro

**Comment by alejandroBlancoPizarro** [comment]
Hi HuangZengt,

The parameter to config the transmission rate at the RX does not matter. 


What surprises me is the driver error, could you please do md5sum of the dhd.ko inside the router and send me the output?

Please, use the router firmware that is in the project.

Best,
Alejandro

**Comment by HuangZengt** [comment]
Hi Alejandro,

I tried the md5sum of the dhd.ko inside the router and the output seems OK.
The md5 file can be seen in attachment:
 
![image](https://user-images.githubusercontent.com/64193566/136679363-25bf1a24-e096-449f-8890-cf5f73172c19.png)


Next, we tried the elder version of the sh-file to compare with the faster version of the sh-file, and there are some differences in receiving packets:

①	 The faster version is unstable. There are three data collection results below, and the number of the packages received are different greatly.
 
![image](https://user-images.githubusercontent.com/64193566/136679372-05654100-31a0-47b1-b843-75c7403c40e8.png)

 
![image](https://user-images.githubusercontent.com/64193566/136679377-f10d0fc5-6dc3-4d03-9acb-116b6b3a0438.png)

![image](https://user-images.githubusercontent.com/64193566/136679379-01375919-48b5-4b61-b901-b6bd34421c07.png)

②	Then, we test the old version of the sh-file (without packet rate configuration, send_collect.sh in hardware_scripts) using the same router firmware (FW_RT-AC86U_300438215098.w), and the received packets are correct. So, I think the usage of router firmware is right. 
![image](https://user-images.githubusercontent.com/64193566/136679384-cf9e6432-ad0c-4bbd-86e4-9f708352411d.png)


③	Next, once we switch to the latest sh-file (send_collect.sh in hardware_scripts_periodically), errors occurred. I guess whether there are errors in send_collect.sh?
 
![image](https://user-images.githubusercontent.com/64193566/136679387-9d4d0b1f-bc15-4a16-b6e1-f9b0c2cc4e49.png)


Wish your help!

Best,

Hjdkl.


attachment :  [ko.zip](https://github.com/IMDEANetworksWNG/UbiLocate/files/7316744/ko.zip)

**Comment by HuangZengt** [comment]
The routers are indeed in AP mode.

**Comment by alejandroBlancoPizarro** [comment]
Closing

**Comment by Zed-Yuan** [comment]
> The routers are indeed in AP mode.

I met the same problem with u, Have u solved it yet? Could u please give me a hand?
