### ISSUE TITLE
Using outgoing signals from different transmit antennas (4 Tx antennas), the estimated AoAs are very different!

### ISSUE THREAD

**Issue by sophiajs1** [IMDEANetworksWNG/UbiLocate#6]
Greetings!

Thanks somuch for the author to share such an excellent tool.

Based on your calibration method, we obtain a full reference CSI matrix for phase offset calibration. However, after phase calibration, when using outgoing signals from different transmit antennas (4 Tx antennas), the estimated AoAs are very different. Here we use 2D-Music to estimate Tof/AoA.
![image](https://user-images.githubusercontent.com/88754162/130324755-830254ec-c7a0-453f-b3e4-ce9f594d4a58.png)

Do the phase differences of these 4*4 antenna data satisfy a function of the AoA/AoD?  Accurate AOA/AoD can be obtained at some locations, but most locations cannot！

Hope you can help me or give some advice to fix this problem.
Thanks.
sophia

**Comment by sophiajs1** [comment]
Another question, I read the ‘Handle_Decompose_3D.m’ and there is a calibration.mat which contains phase offset calibration data. I wonder why there needs to calibrate TX_delay? And how to obtain the TX_delay_coef.mat? @alejandroBlancoPizarro Thanks.

**Comment by alejandroBlancoPizarro** [comment]
Hi,

@sophiajs1, do you still have issues? I cannot see why the AoA estimates from different spatial stream do not match. Did you try to collect CSI measurements by cable and  estimate the AoAs? You can use the data that you collected to do the calibration.

Concerning the data for Cal.mat, one of the author did it. I need to check with him how he was able to measure it.

Best,
Alejandro

**Comment by sophiajs1** [comment]
@alejandroBlancoPizarro, I still have the issues. I use the CSI measurements collected by cable to estimate the AoAs from different spatial stream. they are same. Then,  I connect TX and RX ports to the antennas and collect the CSI measurements, which are calibrated with the cable data. However, the estimated AoAs from different spatial streams are very different. Is there something wrong with my operation?  and we look forward to your new version which can tune the packet rate.

I wish your help.

Thanks.
sophia

**Comment by alejandroBlancoPizarro** [comment]
Hi sophia,

One question, after unplugging the cables from the splitter/combiner, have you connected them directly to the antennas? I mean without any modification.

Also, the logical index of the CSI chains in matlab correspond to the physical position of the array?

Best,
Alejandro

**Comment by sophiajs1** [comment]
Hi, Alejandro,

Thank you for your reply. I  do connect the cables directly to the antennas without any modification.   
![(_{F2~I$N)21BN@II0KBMZW](https://user-images.githubusercontent.com/88754162/132308953-bae616b6-e16e-4dfe-8970-d82406f38769.png)
I use the position of the array in this figure as the logical index of the CSI data. Have you observed these AoAs estimated by different spatial streams?

Best,
Sophia

**Comment by alejandroBlancoPizarro** [comment]
Hi Sophia,

I have never observed the AoAs from different spatial stream do not match between each other. Please, to debug it act as follows:

1) Take outdoor measurements to avoid multipath as much as possible
2) Try Handle_Decompose_2D and Handle_Decompose_3D

Afterwards, let me know if you still see the same behavior.

Best,
Alejandro
