### ISSUE TITLE
Undocumented Constant Calibration Values

### ISSUE THREAD

**Issue by wshunter** [IMDEANetworksWNG/UbiLocate#7]
Hello, the provided "decompose_2d" function uses some calibration values BP0_AoA and BP0_AoD. I can't find any reference to these files elsewhere in the code or an explanation of what they do. They seem to be some kind of pre collected compensation data, but why in only a 1x4 shape? I see this was brought up in a past issue but remains unresolved. Any help would be much appreciated.

**Comment by alejandroBlancoPizarro** [comment]
Hi wshunter,

I added the answer of your question in [FAQs](https://github.com/IMDEANetworksWNG/UbiLocate/blob/main/README.md#faqs)

Take a look at it.

Best,
Alejandro
